import { useEffect, useRef, useState } from "react";

type Msg={role:"user"|"assistant";text:string};
const starters=["I need VPN access","Guest Wi-Fi for a visitor","Check my request status"];
export default function App(){
 const [messages,setMessages]=useState<Msg[]>([{role:"assistant",text:"Welcome. I can help you request network access or check an existing request. What kind of access do you need?"}]);
 const [input,setInput]=useState(""); const [busy,setBusy]=useState(false); const [conversation,setConversation]=useState(""); const end=useRef<HTMLDivElement>(null);
 useEffect(()=>end.current?.scrollIntoView({behavior:"smooth"}),[messages,busy]);
 async function send(text=input){if(!text.trim()||busy)return;setInput("");setMessages(m=>[...m,{role:"user",text}]);setBusy(true);let answer="";
  try{const r=await fetch((window as any).__AGENT_URL__,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:text,conversation_id:conversation||undefined})});if(!r.ok)throw new Error(`Request failed (${r.status})`);const reader=r.body?.getReader();const dec=new TextDecoder();let buffer="";while(reader){const {done,value}=await reader.read();if(done)break;buffer+=dec.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){if(!line.trim())continue;let e:any;try{e=JSON.parse(line)}catch{continue}if(e.type==="conversation"&&!conversation){setConversation(e.conversationId);history.replaceState({},"",`${location.pathname}?conversation=${encodeURIComponent(e.conversationId)}`)}if(e.type==="text-delta"||e.type==="text_delta")answer+=e.delta||e.text||"";if(e.type==="text"&&e.text)answer+=e.text;setMessages(m=>{const base=m.filter((x,i)=>!(i===m.length-1&&x.role==="assistant"&&x.text.startsWith(answer.slice(0,8))));return answer?[...base,{role:"assistant",text:answer}]:base});}}
  }catch(e:any){setMessages(m=>[...m,{role:"assistant",text:`I couldn't complete that turn: ${e.message}. Please try again.`}]);}finally{setBusy(false)}}
 return <main className="shell"><aside><div className="brand"><span className="mark">N</span><div><b>Network Access</b><small>Secure request concierge</small></div></div><div className="signal"><i/> Policy engine online</div><section><p>SUPPORTED ACCESS</p>{["VPN","VLAN & segments","Guest Wi-Fi"].map(x=><div className="nav" key={x}>{x}<span>→</span></div>)}</section><footer><span className="shield">◆</span><div><b>Authenticated workspace</b><small>Your activity is audited</small></div></footer></aside>
 <section className="chat"><header><div><p>ACCESS CONCIERGE</p><h1>Tell us what you need.</h1></div><span className="secure">SSO protected</span></header><div className="thread">{messages.map((m,i)=><div className={`row ${m.role}`} key={i}>{m.role==="assistant"&&<span className="avatar">N</span>}<div className="bubble">{m.text}</div></div>)}{busy&&<div className="row assistant"><span className="avatar">N</span><div className="bubble typing"><i/><i/><i/></div></div>}<div ref={end}/></div>
 <div className="composer">{messages.length===1&&<div className="chips">{starters.map(s=><button onClick={()=>send(s)} key={s}>{s}</button>)}</div>}<div className="input"><textarea aria-label="Message" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Describe the access you need…"/><button aria-label="Send" disabled={busy||!input.trim()} onClick={()=>send()}>↑</button></div><small>Access is granted only after policy evaluation. Sensitive requests require human approval.</small></div></section></main>}
