color = "purple"
output = true
route = "/architecture-analyze"
route_auth = "space"
route_type = "api"
connectors = [{ name = "anthropic-se-demos-please-only-use-this-one", type = "anthropic" }]
timeout = 240
